<a href="https://colab.research.google.com/github/ManelBoucenna/AI-s-code-repository/blob/master/Predict_Diabetes_w_t_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [32]:
data = pd.read_csv('https://raw.githubusercontent.com/SridharCR/Diabetes_Prediction/master/Data/diabetes.csv')
data.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [15]:
zero_not_accepted = ['Glucose', 'BloodPressure','SkinThickness','Insulin','BMI']

for column in zero_not_accepted:
  data[column] = data[column].replace(0,np.NaN)
  mean = int(data[column].mean(skipna=True))
  data[column] = data[column].replace(np.NaN, mean)

In [44]:
X = data.iloc[:,:8].values
y = data.iloc[:,8].values

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0, test_size = .2)

In [45]:
# Scale when an algo computes a distance

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [46]:
X_train[:5]

array([[ 0.90832902,  0.91569367,  0.44912368,  0.52222619,  0.3736349 ,
         0.37852648,  0.67740401,  1.69955804],
       [ 0.03644676, -0.75182191, -0.47230103,  0.14814855, -0.69965674,
        -0.50667229, -0.07049698, -0.96569189],
       [-1.12606292,  1.38763205,  1.06340683,  0.77161128,  5.09271083,
         2.54094063, -0.11855487, -0.88240283],
       [-0.8354355 , -0.37427121, -0.67706208,  0.02345601,  0.45029859,
        -0.88604319,  1.10091422, -0.88240283],
       [ 1.19895644, -0.02818307, -3.54371676, -1.28581572, -0.69965674,
        -0.27904975, -0.85143778,  0.36693308]])

In [47]:
classifier = KNeighborsClassifier(n_neighbors= 11, p = 2, metric = 'euclidean')
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=11, p=2,
                     weights='uniform')

In [48]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score

In [49]:
accuracy_score(y_test, y_pred)

0.8051948051948052

In [50]:
confusion_matrix(y_test, y_pred)

array([[95, 12],
       [18, 29]])

In [51]:
f1_score(y_test, y_pred)

0.6590909090909092